/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT2_CLKOUTSEL_FLEXBUS 0x00u /*!<@brief CLKOUT select: FlexBus CLKOUT */

/*! @name PORTC3 (number 73), J1[16]
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_CLOCK_20_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define CUBE_CLOCK_20_PIN 3U                   /*!<@brief PORT pin number */
#define CUBE_CLOCK_20_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTC4 (number 76), J2[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_TMC429_INT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define CUBE_TMC429_INT_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_TMC429_INT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define CUBE_TMC429_INT_PIN 4U                   /*!<@brief PORT pin number */
#define CUBE_TMC429_INT_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTC2 (number 72), J1[14]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_X_LIMIT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define CUBE_X_LIMIT_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_X_LIMIT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define CUBE_X_LIMIT_PIN 2U                   /*!<@brief PORT pin number */
#define CUBE_X_LIMIT_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC17 (number 91), J1[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_Y_LIMIT_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define CUBE_Y_LIMIT_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_Y_LIMIT_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define CUBE_Y_LIMIT_PIN 17U                   /*!<@brief PORT pin number */
#define CUBE_Y_LIMIT_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTC16 (number 90), J1[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_Z_LIMIT_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define CUBE_Z_LIMIT_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_Z_LIMIT_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define CUBE_Z_LIMIT_PIN 16U                   /*!<@brief PORT pin number */
#define CUBE_Z_LIMIT_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTC0 (number 70), J1[11]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_A_FAULT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define CUBE_A_FAULT_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_A_FAULT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define CUBE_A_FAULT_PIN 0U                   /*!<@brief PORT pin number */
#define CUBE_A_FAULT_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC9 (number 81), J1[9]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_B_FAULT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define CUBE_B_FAULT_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_B_FAULT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define CUBE_B_FAULT_PIN 9U                   /*!<@brief PORT pin number */
#define CUBE_B_FAULT_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTC7 (number 79), J1[13]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_Z1_FAULT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define CUBE_Z1_FAULT_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_Z1_FAULT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define CUBE_Z1_FAULT_PIN 7U                   /*!<@brief PORT pin number */
#define CUBE_Z1_FAULT_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTC5 (number 77), J1[15]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_Z2_FAULT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define CUBE_Z2_FAULT_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_Z2_FAULT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define CUBE_Z2_FAULT_PIN 5U                   /*!<@brief PORT pin number */
#define CUBE_Z2_FAULT_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTB18 (number 64), J1[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_A_ENABLE_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define CUBE_A_ENABLE_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_A_ENABLE_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define CUBE_A_ENABLE_PIN 18U                   /*!<@brief PORT pin number */
#define CUBE_A_ENABLE_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTB19 (number 65), J1[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_B_ENABLE_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define CUBE_B_ENABLE_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_B_ENABLE_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define CUBE_B_ENABLE_PIN 19U                   /*!<@brief PORT pin number */
#define CUBE_B_ENABLE_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTB23 (number 69), J1[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_Z1_ENABLE_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define CUBE_Z1_ENABLE_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_Z1_ENABLE_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define CUBE_Z1_ENABLE_PIN 23U                   /*!<@brief PORT pin number */
#define CUBE_Z1_ENABLE_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTB9 (number 57), J1[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_Z2_ENABLE_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define CUBE_Z2_ENABLE_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_Z2_ENABLE_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define CUBE_Z2_ENABLE_PIN 9U                   /*!<@brief PORT pin number */
#define CUBE_Z2_ENABLE_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTC10 (number 82), J4[12]
  @{ */

/* Symbols to be used with GPIO driver */
#define CUBE_TOGGLE_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define CUBE_TOGGLE_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define CUBE_TOGGLE_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define CUBE_TOGGLE_PIN 10U                   /*!<@brief PORT pin number */
#define CUBE_TOGGLE_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void CUBE_Pins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_UART0_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define CUBE_UART0_TX_PIN 17U                   /*!<@brief PORT pin number */
#define CUBE_UART0_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_UART0_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define CUBE_UART0_RX_PIN 16U                   /*!<@brief PORT pin number */
#define CUBE_UART0_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void CUBE_UART0Pins(void);

/*! @name PORTE25 (number 32), J2[18]/U8[6]/I2C0_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_I2C_SDA_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define CUBE_I2C_SDA_PIN 25U                   /*!<@brief PORT pin number */
#define CUBE_I2C_SDA_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTE24 (number 31), J2[20]/U8[4]/I2C0_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_I2C_SCL_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define CUBE_I2C_SCL_PIN 24U                   /*!<@brief PORT pin number */
#define CUBE_I2C_SCL_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void CUBE_I2CPins(void);

/*! @name PORTD0 (number 93), J2[6]
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_SPI_CS_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define CUBE_SPI_CS_PIN 0U                   /*!<@brief PORT pin number */
#define CUBE_SPI_CS_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTD1 (number 94), J2[12]
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_SPI_CLK_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define CUBE_SPI_CLK_PIN 1U                   /*!<@brief PORT pin number */
#define CUBE_SPI_CLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*! @name PORTD2 (number 95), J2[8]
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_SPI_MOSI_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define CUBE_SPI_MOSI_PIN 2U                   /*!<@brief PORT pin number */
#define CUBE_SPI_MOSI_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTD3 (number 96), J2[10]
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_SPI_MISO_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define CUBE_SPI_MISO_PIN 3U                   /*!<@brief PORT pin number */
#define CUBE_SPI_MISO_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void CUBE_SPIPins(void);

/*! @name PORTB10 (number 58), J4[6]
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_UART3_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define CUBE_UART3_RX_PIN 10U                   /*!<@brief PORT pin number */
#define CUBE_UART3_RX_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTB11 (number 59), J4[8]
  @{ */

/* Symbols to be used with PORT driver */
#define CUBE_UART3_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define CUBE_UART3_TX_PIN 11U                   /*!<@brief PORT pin number */
#define CUBE_UART3_TX_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void CUBE_UART3Pins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
