/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "cube.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(position, position, AUTO)


PB_BIND(spi_transfer_payload, spi_transfer_payload, AUTO)


PB_BIND(i2c_transfer_payload, i2c_transfer_payload, AUTO)


PB_BIND(data_reply_payload, data_reply_payload, AUTO)


PB_BIND(gpio_config_payload, gpio_config_payload, AUTO)


PB_BIND(param_config_payload, param_config_payload, AUTO)


PB_BIND(command_msg, command_msg, AUTO)


PB_BIND(reply_msg, reply_msg, AUTO)


PB_BIND(status_msg, status_msg, AUTO)





